export const TEST_CENTERS = new Set([
  'Aberdeen North',
  'Aberdeen South (Cove)',
  'Abergavenny',
  'Aberystwyth (Park Avenue)',
  'Airdrie',
  'Alness',
  'Alnwick',
  'Arbroath',
  'Ashfield',
  'Ashford (Kent)',
  'Ashford (London Middlesex)',
  'Atherton (Manchester)',
  'Aylesbury',
  'Ayr',
  'Bala',
  'Ballater',
  'Banbury',
  'Banff',
  'Bangor',
  'Barking (Tanner Street)',
  'Barnet (London)',
  'Barnsley',
  'Barnstaple',
  'Barra',
  'Barrow In Furness',
  'Barry',
  'Basildon',
  'Basingstoke',
  'Belvedere (London)',
  'Benbecula Island',
  'Berwick-On-Tweed',
  'Beverley LGV',
  'Birmingham (Garretts Green)',
  'Birmingham (Kings Heath)',
  'Birmingham (Kingstanding)',
  'Birmingham (Shirley)',
  'Birmingham (South Yardley)',
  'Birmingham (Sutton Coldfield)',
  'Birmingham (Wyndley)',
  'Bishopbriggs',
  'Bishops Stortford',
  'Blackburn with Darwen',
  'Blackpool',
  'Bletchley',
  'Blyth',
  'Bodmin',
  'Bolton (Manchester)',
  'Borehamwood (London)',
  'Boston',
  'Bradford (Heaton)',
  'Bradford (Thornbury)',
  'Brecon',
  'Bredbury (Manchester)',
  'Brentwood (London)',
  'Bridgend',
  'Bridlington',
  'Bristol (Avonmouth)',
  'Bristol (Brislington)',
  'Bristol (Kingswood)',
  'Brodick (Isle of Arran)',
  'Bromley (London)',
  'Buckie',
  'Burgess Hill',
  'Burton on Trent',
  'Bury (Manchester)',
  'Bury St Edmunds',
  'Buxton',
  'Camborne',
  'Cambridge (Brookmount Court)',
  'Campbeltown',
  'Canterbury',
  'Cardiff (Llanishen)',
  'Cardigan',
  'Cardington',
  'Carlisle',
  'Carmarthen',
  'Castle Douglas',
  'Chadderton',
  'Cheetham Hill (Manchester)',
  'Chelmsford (Hanbury Road)',
  'Cheltenham',
  'Chertsey (London)',
  'Chester',
  'Chesterfield',
  'Chichester',
  'Chingford (London)',
  'Chippenham',
  'Chorley',
  'Clacton-on-Sea',
  'Colchester',
  'Coventry',
  'Crawley',
  'Crewe',
  'Croydon (London)',
  'Cumnock',
  'Darlington',
  'Derby (Alvaston)',
  'Doncaster',
  'Dorchester',
  'Dudley',
  'Dumbarton',
  'Dumfries',
  'Dundee',
  'Dunfermline (Vine)',
  'Dunoon',
  'Duns',
  'Durham',
  'East Kilbride',
  'Eastbourne',
  'Edinburgh (Currie)',
  'Edinburgh (Musselburgh)',
  'Elgin',
  'Elswick',
  'Enfield (Innova Business Park)',
  'Erith (London)',
  'Exeter',
  'Farnborough',
  'Featherstone',
  'Folkestone',
  'Forfar',
  'Fort William',
  'Fraserburgh',
  'Gairloch',
  'Galashiels',
  'Gateshead',
  'Gillingham',
  'Girvan',
  'Glasgow (Anniesland)',
  'Glasgow (Baillieston)',
  'Glasgow (Shieldhall)',
  'Gloucester',
  'Golspie',
  'Goodmayes (London)',
  'Gosforth',
  'Grangemouth',
  'Grantham (Somerby)',
  'Grantown-On-Spey',
  'Greenford (Horsenden Lane)',
  'Greenock',
  'Grimsby Coldwater',
  'Guildford',
  'Haddington',
  'Halifax',
  'Hamilton',
  'Hartlepool',
  'Hastings (Ore)',
  'Hawick',
  'Heckmondwike',
  'Hendon (London)',
  'Hereford',
  'Herne Bay',
  'Hexham',
  'Heysham',
  'High Wycombe',
  'Hinckley',
  'Hither Green (London)',
  'Hornchurch (London)',
  'Horsforth',
  'Huddersfield',
  'Hull',
  'Huntly',
  'Hyde (Manchester)',
  'Inveraray',
  'Inverness (Seafield Road)',
  'Inverurie',
  'Ipswich',
  'Irvine',
  'Islay Island',
  'Isle of Skye (Portree)',
  'Isleworth (Fleming Way)',
  'Kelso',
  'Kendal (Oxenholme Road)',
  'Kettering',
  'Kings Lynn',
  'Kingussie',
  'Kirkcaldy',
  'Knaresborough',
  'Kyle of Lochalsh',
  'Lanark',
  'Lancing',
  'Launceston',
  'Lee On The Solent',
  'Leeds',
  'Leicester (Cannock Street)',
  'Leicester (Wigston)',
  'Leighton Buzzard (Stanbridge Road)',
  'Lerwick',
  'Letchworth',
  'Lichfield',
  'Lincoln',
  'Livingston',
  'Llanelli',
  'Llantrisant',
  'Lochgilphead',
  'Loughborough',
  'Loughton (London)',
  'Louth',
  'Lowestoft(Mobbs Way)',
  'Ludlow',
  'Luton',
  'Macclesfield',
  'Maidstone',
  'Mallaig',
  'Malton',
  'Melton Mowbray',
  'Merthyr Tydfil',
  'Middlesbrough',
  'Mill Hill (London)',
  'Mitcham (London)',
  'Monmouth',
  'Montrose',
  'Morden (London)',
  'Nelson',
  'Newbury (Hambridge Lane)',
  'Newport (Gwent)',
  'Newport IOW (Innovation Centre)',
  'Newton Abbot',
  'Newton Stewart',
  'Newtown',
  'Norris Green (Liverpool)',
  'Northallerton',
  'Northampton',
  'Northwich',
  'Norwich (Jupiter Road)',
  'Norwich (Peachman Way)',
  'Nottingham (Chilwell)',
  'Nottingham (Colwick)',
  'Nuneaton',
  'Oban',
  'Orkney',
  'Oswestry',
  'Oxford (Cowley)',
  'Paisley',
  'Peebles',
  'Pembroke Dock',
  'Perth (Arran Road)',
  'Peterborough',
  'Peterhead',
  'Pinner (London)',
  'Plymouth',
  'Pontefract',
  'Poole',
  'Portsmouth',
  'Preston',
  'Pwllheli',
  'Reading',
  'Redditch',
  'Redhill Aerodrome',
  'Rhyl',
  'Rochdale (Manchester)',
  'Rotherham',
  'Rothesay',
  'Rugby',
  'Sale (Manchester)',
  'Salisbury',
  'Scarborough',
  'Scunthorpe',
  'Sevenoaks',
  'Sheffield (Handsworth)',
  'Sheffield (Middlewood Road)',
  'Shrewsbury',
  'Sidcup (London)',
  'Skegness',
  'Skipton',
  'Slough (London)',
  'South Shields',
  'Southall (London)',
  'Southampton (Forest Hills)',
  'Southampton (Maybush)',
  'Southend-on-Sea',
  'Southport (Liverpool)',
  'Speke (Liverpool)',
  'St Albans',
  'St Helens (Liverpool)',
  'Stafford',
  'Steeton',
  'Stevenage',
  'Stirling',
  'Stoke-On-Trent (Cobridge)',
  'Stoke-on-Trent (Newcastle-Under-Lyme)',
  'Stornoway',
  'Stranraer',
  'Sunderland',
  'Swansea',
  'Swindon',
  'Taunton',
  'Telford',
  'Thurso',
  'Tilbury',
  'Tolworth (London)',
  'Tottenham',
  'Trowbridge',
  'Tunbridge Wells',
  'Ullapool',
  'Upton',
  'Uxbridge (London)',
  'Wakefield',
  'Wallasey',
  'Wanstead (London)',
  'Warrington',
  'Warwick (Wedgenock House)',
  'Watford',
  'Watnall',
  'Wednesbury',
  'Wellingborough',
  'West Didsbury (Manchester)',
  'West Wickham (London)',
  'Weston-super-Mare',
  'Whitby',
  'Whitchurch',
  'Wick',
  'Widnes',
  'Winchester',
  'Wolverhampton',
  'Wood Green (London)',
  'Worcester',
  'Workington',
  'Worksop',
  'Wrexham',
  'Yeading (London)',
  'Yeovil',
  'York'
])
